# hosts.yaml
all:
  hosts:
    k8s-cp-01:
      ansible_host: 172.16.0.2
      ip: 172.16.0.2
      access_ip: 172.16.0.2
    k8s-wrk-01:
      ansible_host: 172.16.0.3
      ip: 172.16.0.3
      access_ip: 172.16.0.3
  children:
    kube_control_plane:
      hosts:
        k8s-cp-01:
    kube_node:
      hosts:
        k8s-cp-01:
        k8s-wrk-01:
    etcd:
      hosts:
        k8s-cp-01:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
